[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[theme]
base="light"
primaryColor="#2ecc71"
backgroundColor="#f8fff2"
secondaryBackgroundColor="#e9fbe7"
textColor="#1b4332"
font="sans serif"


