# =========================
# 🔐 Streamlit Secrets File
# =========================

[twilio]
account_sid = "AC5246375b37e2c84a17d62df1cfbbad55"
auth_token = "91c9ff0cd63442e76d58f918b0c4feec"
verify_sid = "VA7a58f41d1ede670f8cb384cb924e90d0"

[supabase]
url = "https://yijetnurzpsdztzhgdho.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiIsInlpamV0bnVyenBzZHp0emhnZGhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4ODQyMjgsImV4cCI6MjA3NTQ2MDIyOH0.5sEOobhtztkhiP55T9GhOQY47bTzv2bPrSlmCvkMC28"
service_role_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiIsInlpamV0bnVyenBzZHp0emhnZGhvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1OTg4NDIyOCwiZXhwIjoyMDc1NDYwMjI4fQ.LL6BAONdUNW3uhuMRR53YLwdtEtd7rGmw2ZZnZU3Z18"
